import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, ChevronRight, CircleHelp, Code2, ExternalLink, FileCode2, GitBranch, HeartPulse, KeyRound, Layers3, LockKeyhole, Network, Rocket, ScrollText, ShieldCheck, Terminal, TestTube2, WalletCards } from "lucide-react";

const nav = [["Overview","overview"],["Quickstart","quickstart"],["Product guide","product"],["Architecture","architecture"],["Smart contract","contract"],["Frontend","frontend"],["Security","security"],["Testing & deploy","testing"]] as const;
const methods = [
  ["initialize", "Create contract state once; set admin and configured SAC token."],
  ["set_role / role_of", "Admin assigns Provider or Insurer role and reads current role."],
  ["register_record / get_record", "Provider + patient co-sign record commitment; read metadata."],
  ["grant_access / has_access", "Patient creates scoped grant; gateway checks live expiry and key version."],
  ["revoke_access / rotate_record", "Patient invalidates a grantee or all stale grants after key rotation."],
  ["set_policy / get_policy", "Insurer configures active patient coverage and per-claim ceiling."],
  ["submit_claim / get_claim", "Patient + provider submit evidence-backed claim; read lifecycle state."],
  ["approve_claim / reject_claim / cancel_claim / pay_claim", "Insurer advances valid state; payout transfers SAC atomically."],
] as const;
const events = ["Initialized","RoleChanged","RecordRegistered","RecordRotated","AccessRequested","AccessGranted","AccessRevoked","PolicySet","ClaimSubmitted","ClaimApproved","ClaimRejected","ClaimCancelled","ClaimPaid"];

function Code({ children }: { children: string }) { return <pre className="docs-code"><code>{children}</code></pre>; }
function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="docs-section scroll-mt-28"><p className="docs-eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>; }

export default function DocsPage() {
  return <main className="docs-page">
    <div className="docs-hero"><div className="docs-hero-grid" /><div className="docs-container docs-hero-inner">
      <div className="docs-kicker"><BookOpen className="size-4" /> Aegis Health documentation</div>
      <h1>Build trust into<br /><span>every care handoff.</span></h1>
      <p className="docs-lede">Technical guide for patient-owned health records, consent controls, and atomic claim settlement on Stellar Soroban.</p>
      <div className="docs-hero-actions"><a href="#quickstart" className="docs-button docs-button-light">Run locally <ArrowRight className="size-4" /></a><a href="https://github.com/rajiv-sys-bot/Aegis-Health" target="_blank" rel="noreferrer" className="docs-button docs-button-ghost">View source <ExternalLink className="size-4" /></a></div>
      <div className="docs-hero-note"><span className="docs-status-dot" /> Stellar testnet demo · no plaintext health data on-chain</div>
    </div></div>
    <div className="docs-container docs-layout">
      <aside className="docs-sidebar"><div className="docs-sidebar-label">On this page</div>{nav.map(([label, href]) => <a key={href} href={`#${href}`} className="docs-side-link">{label}<ChevronRight className="size-3.5" /></a>)}<div className="docs-sidebar-card"><ShieldCheck className="size-5 text-brand-600" /><strong>Trust model</strong><span>Hashes, grants, events. Payloads stay private.</span></div></aside>
      <article className="docs-content">
        <Section id="overview" eyebrow="01 · Overview" title="Aegis in one minute"><p>Aegis Health gives patients one verifiable access layer for records shared across providers. Browser encrypts content before storage; Soroban stores commitments, consent state, roles, policies, and claim transitions.</p><div className="docs-card-grid">{[[LockKeyhole,"Private by design","Only SHA-256 hashes, encrypted-key commitments, and permission metadata reach the ledger."],[WalletCards,"Wallet-native consent","Freighter signs every state change. No passwords or app-held private keys."],[ScrollText,"Replayable audit","Typed contract events feed deterministic frontend reducers and the audit view."],[Network,"Atomic settlement","Approved provider claims pay in configured SAC token within one contract flow."]].map(([Icon,title,copy]) => { const I = Icon as typeof LockKeyhole; return <div className="docs-card" key={title as string}><I className="size-5 text-brand-600" /><h3>{title as string}</h3><p>{copy as string}</p></div>; })}</div><div className="docs-callout"><CircleHelp className="size-5" /><div><strong>Demo boundary</strong><p>Testnet demo only. Encrypted storage transport, key-envelope delivery, and clinical workflows are integration points—not production medical infrastructure.</p></div></div></Section>
        <Section id="quickstart" eyebrow="02 · Quickstart" title="Run seeded testnet demo"><p>Requirements: Node.js 22+, npm, Rust, and Stellar CLI with Soroban support. Setup creates demo accounts, deploys a fresh contract, seeds records/grants/policy/claims, and writes local configuration.</p><Code>{`npm install
npm run setup
npm run dev`}</Code><ol className="docs-steps"><li><b>Keep Freighter on Stellar Testnet.</b> Import accounts from gitignored <code>scripts/aegis-accounts.local.env</code>.</li><li><b>Open app.</b> Visit <code>http://localhost:3000</code> and connect wallet for desired role.</li><li><b>Inspect chain state.</b> Use Audit log, Stellar Expert links, or <code>npm run smoke</code>.</li></ol><div className="docs-inline-links"><Link href="/">Open app <ArrowRight className="size-4" /></Link><a href="https://github.com/rajiv-sys-bot/Aegis-Health/blob/main/scripts/setup.sh" target="_blank" rel="noreferrer">Read setup script <ExternalLink className="size-4" /></a></div></Section>
        <Section id="product" eyebrow="03 · Product guide" title="Role-based workflows">{[["01",HeartPulse,"Patient","Connect wallet → My records → grant provider/insurer access with expiry → revoke or rotate key → review audit trail."],["02",Layers3,"Clinic / provider","Connect Provider wallet → Clinic → enter patient + record hash → request access → verify live grant before releasing or fetching encrypted payload."],["03",ScrollText,"Insurer","Connect Insurer wallet → Claims → review active policy and evidence → approve/reject → pay approved claim atomically in demo SAC."],["04",GitBranch,"Admin","Connect contract admin → Admin → inspect role assignments and configure Provider or Insurer access. Admin cannot assign a role to itself."]].map(([num,Icon,title,copy]) => { const I = Icon as typeof HeartPulse; return <div className="docs-workflow" key={title as string}><div className="docs-workflow-number">{num as string}</div><div><h3><I className="size-5" /> {title as string}</h3><p>{copy as string}</p></div></div>; })}</Section>
        <Section id="architecture" eyebrow="04 · Architecture" title="Browser-to-ledger, no app backend"><p>Next.js App Router renders role-specific views. Browser reads Soroban through RPC and sends state-changing transactions through Freighter. There is no API route or application database in this repository.</p><div className="docs-architecture">{[[WalletCards,"Browser","Next.js UI + Freighter"],[Network,"Soroban RPC","typed reads + signed XDR"],[Code2,"Contract","state, auth, events"]].map(([Icon,title,copy],i) => { const I = Icon as typeof Code2; return <span key={title as string} className="docs-arch-wrap"><div className="docs-arch-node"><I /><b>{title as string}</b><span>{copy as string}</span></div>{i < 2 && <span className="docs-arch-arrow">↔</span>}</span>; })}</div><Code>{`app/                         Routes and layout
components/                  Shell, wallet, modals, UI
hooks/                       Event + view loading hooks
lib/stellar.ts               Read client, Freighter signer, tx errors
lib/reads.ts                 Typed point reads and view models
lib/events.ts                Soroban event decoding
lib/event-reducers.ts        Deterministic event projections
contract/src/                Rust Soroban contract + tests
scripts/setup.sh             Testnet deployment and seed flow`}</Code></Section>
        <Section id="contract" eyebrow="05 · Smart contract" title="On-chain rules and interfaces"><p><code>MedicalRecordsContract</code> is implemented in <code>contract/src/lib.rs</code>. Authorization, expiry, key-version invalidation, coverage limits, and claim state transitions execute on-chain.</p><div className="docs-methods">{methods.map(([method,description]) => <div key={method}><code>{method}</code><span>{description}</span></div>)}</div><h3 className="docs-subhead">Stored data</h3><p><code>MedicalRecord</code> stores patient/provider, content hash, locator hash, timestamps, and key version. <code>AccessGrant</code> stores parties, expiry, key version, and encrypted-key commitment. <code>Policy</code> stores insurer/patient, token, limit, expiry, active flag. <code>Claim</code> stores participants, record, token, amount, evidence hash, timestamp, and status.</p><h3 className="docs-subhead">Events</h3><div className="docs-tags">{events.map(event => <span key={event}>{event}</span>)}</div></Section>
        <Section id="frontend" eyebrow="06 · Frontend implementation" title="Reads, writes, and projections"><p>Generated TypeScript bindings keep contract calls typed. <code>anonymousClient()</code> handles no-signer reads; <code>contractClient(publicKey)</code> injects Freighter signing. <code>runWrite()</code> assembles, simulates, signs, submits, and returns transaction hash.</p><div className="docs-mini-grid">{[[FileCode2,"Point reads","lib/reads.ts normalizes Soroban values into JSON-safe view models."],[ScrollText,"Event projections","lib/event-reducers.ts folds events oldest-to-newest for grants, claims, requests, and roles."],[TestTube2,"Resilient UI","Loading skeletons, empty states, retryable errors, toasts, reduced-motion support."]].map(([Icon,title,copy]) => { const I = Icon as typeof FileCode2; return <div key={title as string}><I /><h3>{title as string}</h3><p>{copy as string}</p></div>; })}</div></Section>
        <Section id="security" eyebrow="07 · Security model" title="What is protected, and where"><div className="docs-security-list">{["Client-side encryption happens before content leaves the user device.","Soroban receives hashes and commitments, never plaintext files or diagnoses.","Grant expiry and key-version matching are enforced by contract state.","Every fetch path must verify live access; revocation takes effect immediately.","Freighter keeps private keys outside the app and signs state changes.","Testnet accounts and demo SAC are not suitable for real data or funds."].map(item => <div key={item}><CheckCircle2 className="size-5 text-success" /><span>{item}</span></div>)}</div><div className="docs-callout docs-callout-warn"><KeyRound className="size-5" /><div><strong>Production work remaining</strong><p>Connect audited encrypted object storage, key management, gateway authorization, monitoring, compliance controls, and real clinical consent policy before any production use.</p></div></div></Section>
        <Section id="testing" eyebrow="08 · Testing & deploy" title="Verify changes before release"><Code>{`npm run test:contract  # Rust/Soroban tests
npm run typecheck       # route types + TypeScript
npm run lint            # ESLint
npm run build           # production build
npm run smoke           # RPC + deployed contract health`}</Code><p>Contract suite covers initialization, grants and key rotation, policy limits, claim authorization, and atomic provider payout. CI repeats contract tests, type checks, route generation, and lint on pushes and pull requests.</p><div className="docs-release"><Rocket className="size-5 text-brand-600" /><div><h3>Deployment checklist</h3><p>Use testnet configuration, keep <code>.env.local</code> and account secrets untracked, run all verification commands, then deploy frontend with public <code>NEXT_PUBLIC_*</code> values only.</p></div></div><div className="docs-inline-links"><a href="https://github.com/rajiv-sys-bot/Aegis-Health" target="_blank" rel="noreferrer">GitHub repository <ExternalLink className="size-4" /></a><a href="https://stellar.expert/explorer/testnet/contract/CAMNUFS7SGCTUQTLNYN7WM5AIEB22X4F3M72VVRMVXWMEQFWZXLFU7C2" target="_blank" rel="noreferrer">Contract on Stellar Expert <ExternalLink className="size-4" /></a></div></Section>
        <footer className="docs-footer"><Terminal className="size-4" /> Aegis Health · Soroban testnet demo · <Link href="/">Back to app</Link></footer>
      </article>
    </div>
  </main>;
}
